### ISSUE TITLE
naming collision detected?

### ISSUE THREAD

**Issue by xiongjiabin** [7kfpun/FinanceReactNative#5]
Error building DepdendencyGraph:
 Error: Naming collision detected: /Users/xiongjiabin/Project/FinanceReactNative-master/node_modules/react-native/Libraries/vendor/react/vendor/core/ExecutionEnvironment.ios.js collides with /Users/xiongjiabin/Project/FinanceReactNative-master/node_modules/react-native-navbar/node_modules/react-native/Libraries/vendor/react/vendor/core/ExecutionEnvironment.ios.js
    at HasteMap._updateHasteMap (/Users/xiongjiabin/Project/FinanceReactNative-master/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/HasteMap.js:123:13)
    at /Users/xiongjiabin/Project/FinanceReactNative-master/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/HasteMap.js:95:28
    at tryCallOne (/Users/xiongjiabin/Project/FinanceReactNative-master/node_modules/promise/lib/core.js:37:12)
    at /Users/xiongjiabin/Project/FinanceReactNative-master/node_modules/promise/lib/core.js:103:15
    at flush (/Users/xiongjiabin/Project/FinanceReactNative-master/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
Process terminated. Press <enter> to close the window

**Comment by 7kfpun** [comment]
Upgrade to react native 0.18.0-rc, it should be fixed.
