### ISSUE TITLE
Error: Naming collision detected

### ISSUE THREAD

**Issue by rendongsc** [7kfpun/FinanceReactNative#6]
FinanceReactNative/node_modules/react-native-swipeout/node_modules/react/node_modules/fbjs/lib/VersionRange.js collides with /Users/daren/ReactNative/Projects/FinanceReactNative/node_modules/react-native/node_modules/fbjs/lib/VersionRange.js
    at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:103:28
    at tryCallOne (/Users/daren/ReactNative/Projects/FinanceReactNative/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/daren/ReactNative/Projects/FinanceReactNative/node_modules/react-native/node_modules/promise/lib/core.js:123:15
    at flush (/Users/daren/ReactNative/Projects/FinanceReactNative/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)

**Comment by rendongsc** [comment]
1) npm install -g npm3
2) rm -rf node_modules
3) update package.json react-native 0.20
4) npm3 install
